// lib/app_initializer.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:stream_video_flutter/stream_video_flutter.dart';
import 'package:stream_video_push_notification/stream_video_push_notification.dart';

import 'app_keys.dart';
import 'tutorial_user.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

class AppInitializer {
  static const _storedUserKey = 'loggedInUserId';

  /// Get the stored user from secure storage
  static Future<TutorialUser?> getStoredUser() async {
    const storage = FlutterSecureStorage();
    final userId = await storage.read(key: _storedUserKey);
    
    if (userId == null) {
      return null;
    }

    try {
      return TutorialUser.users.firstWhere(
        (user) => user.user.id == userId,
      );
    } catch (e) {
      // User not found in hardcoded list
      return null;
    }
  }

  /// Store user ID in secure storage
  static Future<void> storeUser(TutorialUser tutorialUser) async {
    const storage = FlutterSecureStorage();
    await storage.write(key: _storedUserKey, value: tutorialUser.user.id);
  }

  /// Clear stored user data
  static Future<void> clearStoredUser() async {
    const storage = FlutterSecureStorage();
    await storage.delete(key: _storedUserKey);
  }

  /// Initialize StreamVideo with ringing support
  static Future<StreamVideo> init(TutorialUser tutorialUser) async {
    // Initialize Firebase
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // Create and configure StreamVideo instance
    return StreamVideo(
      AppKeys.streamApiKey,
      user: tutorialUser.user,
      userToken: tutorialUser.token,
      options: const StreamVideoOptions(
        keepConnectionsAliveWhenInBackground: true,
      ),
      pushNotificationManagerProvider: StreamVideoPushNotificationManager.create(
        iosPushProvider: const StreamVideoPushProvider.apn(
          name: AppKeys.iosPushProviderName,
        ),
        androidPushProvider: const StreamVideoPushProvider.firebase(
          name: AppKeys.androidPushProviderName,
        ),
        pushParams: const StreamVideoPushParams(
          appName: 'Stream Video Call',
          ios: IOSParams(iconName: 'IconMask'),
        ),
        registerApnDeviceToken: true,
      ),
    )..connect();
  }
}