// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdP49DiQZooBhvQaUpEzyhyVSjFFG1SSI',
    appId: '1:564591146605:web:d3286f8cbde9b675313164',
    messagingSenderId: '564591146605',
    projectId: 'notificationforlailaolab',
    authDomain: 'notificationforlailaolab.firebaseapp.com',
    storageBucket: 'notificationforlailaolab.firebasestorage.app',
    measurementId: 'G-R2GS1K0KTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4aZDk18_7J8cAsWlRKaU3FklZDeDVR8o',
    appId: '1:564591146605:android:d5cae495e35a69a5313164',
    messagingSenderId: '564591146605',
    projectId: 'notificationforlailaolab',
    storageBucket: 'notificationforlailaolab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv36qID86PzG1d9IXQtdc7hWl0264nM8U',
    appId: '1:564591146605:ios:975e5853f1e009de313164',
    messagingSenderId: '564591146605',
    projectId: 'notificationforlailaolab',
    storageBucket: 'notificationforlailaolab.firebasestorage.app',
    iosBundleId: 'com.example.streamVideoTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv36qID86PzG1d9IXQtdc7hWl0264nM8U',
    appId: '1:564591146605:ios:975e5853f1e009de313164',
    messagingSenderId: '564591146605',
    projectId: 'notificationforlailaolab',
    storageBucket: 'notificationforlailaolab.firebasestorage.app',
    iosBundleId: 'com.example.streamVideoTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdP49DiQZooBhvQaUpEzyhyVSjFFG1SSI',
    appId: '1:564591146605:web:d00e9ab1f5585ba3313164',
    messagingSenderId: '564591146605',
    projectId: 'notificationforlailaolab',
    authDomain: 'notificationforlailaolab.firebaseapp.com',
    storageBucket: 'notificationforlailaolab.firebasestorage.app',
    measurementId: 'G-Q088MD927V',
  );
}
