// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrtKk410jAhtPJl5AGboNyQ6OCWKxxqs',
    appId: '1:465683453774:web:6c9082ee6d06f33016301f',
    messagingSenderId: '465683453774',
    projectId: 'niwnergetstream',
    authDomain: 'niwnergetstream.firebaseapp.com',
    storageBucket: 'niwnergetstream.firebasestorage.app',
    measurementId: 'G-8NQK12R7DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA5BZa9CS2kkgHZVlb6wb2XAT2h0bMtDY',
    appId: '1:465683453774:android:01f1903fb88ef2df16301f',
    messagingSenderId: '465683453774',
    projectId: 'niwnergetstream',
    storageBucket: 'niwnergetstream.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCxEkwZKDW8vUB7LtFSfe8GHfIwE1hag',
    appId: '1:465683453774:ios:5394c0eaad1d67f016301f',
    messagingSenderId: '465683453774',
    projectId: 'niwnergetstream',
    storageBucket: 'niwnergetstream.firebasestorage.app',
    iosClientId: '465683453774-dbkdf6mhtrh14k8b0mceucp0kmb52qcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamVideoTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCxEkwZKDW8vUB7LtFSfe8GHfIwE1hag',
    appId: '1:465683453774:ios:5394c0eaad1d67f016301f',
    messagingSenderId: '465683453774',
    projectId: 'niwnergetstream',
    storageBucket: 'niwnergetstream.firebasestorage.app',
    iosClientId: '465683453774-dbkdf6mhtrh14k8b0mceucp0kmb52qcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamVideoTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxrtKk410jAhtPJl5AGboNyQ6OCWKxxqs',
    appId: '1:465683453774:web:d93053715ec5358a16301f',
    messagingSenderId: '465683453774',
    projectId: 'niwnergetstream',
    authDomain: 'niwnergetstream.firebaseapp.com',
    storageBucket: 'niwnergetstream.firebasestorage.app',
    measurementId: 'G-024DNX6J08',
  );
}
